version: "3"
services:
  nzbtoproxy:
    build: ./docker/.
    ports:
      - "8080:80"
#      - "4433:443"
    volumes:
      - .:/var/www
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    container_name: 'nzb.to-indexer'
    networks:
      - usenet

  torproxy:
    build: ./docker2/.
    ports:
      - "9150:9150"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    container_name: "torproxy"
    networks:
      - usenet

networks:
  usenet:
    external: true
