version: '3'
services:
  vscode:
    image: "nzb.to-indexer"
    build: 
      context: ../docker/.
      dockerfile: Dockerfile
    command: ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
    ports:
      - "8080:80"
    volumes: 
      - ../:/workspace
    networks:
      - vscode
      
#    torproxy:
#        build: ../docker2/.
#        volumes:
#          - /etc/timezone:/etc/timezone:ro
#          - /etc/localtime:/etc/localtime:ro
#        ports:
#          - "9150:9150"
#        networks:
#          - vscode

networks:
  vscode:
    external: true
